name: Check Minecraft Server

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Load repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mcstatus google-cloud-compute
      - name: Run python script(s)
        env:
          MINECRAFT_SERVER_ADDRESS: ${{ secrets.MINECRAFT_SERVER_ADDRESS }}
          MINECRAFT_VM_SERVICE_ACCOUNT: ${{ secrets.MINECRAFT_VM_SERVICE_ACCOUNT }}
          MINECRAFT_PROJECT_ID: ${{ secrets.MINECRAFT_PROJECT_ID }}
          MINECRAFT_PROJECT_ZONE: ${{ secrets.MINECRAFT_PROJECT_ZONE }}
          MINECRAFT_VM_NAME: ${{ secrets.MINECRAFT_VM_NAME }}
        run: |
          python check_minecraft_server.py
